### ISSUE TITLE
Duplicate Fan Id

### ISSUE THREAD

**Issue by WenXin20** [Zundrel/How-Bout-That-Furniture#2]
Forge 2185
Mod v1.2.0
After updating this mod, the game won't launch because of another mod that uses the duplicate id TileEntityFan.

**Comment by Shrimpstress** [comment]
Will be fixed in just a bit. Sorry about the inconvenience.

Do you have any idea what other mod is causing this however?

**Comment by WenXin20** [comment]
It's okay, and thanks.
 I think it's the Grim Pack Mod, which has a fan.

**Comment by Shrimpstress** [comment]
It should be fixed in the latest 1.2.1 update.
