### ISSUE TITLE
[Bug?] Fences and Furniture

### ISSUE THREAD

**Issue by ghost** [Zundrel/How-Bout-That-Furniture#4]
There are several items, such as stools, chairs, fans, etc. that I don't think fences should connect to, as it can muddle the appearance of a build.

**Comment by Shrimpstress** [comment]
It's a bug and I have found the cause. Build with a fix will be uploaded within the next 30 minutes or so.

**Comment by Shrimpstress** [comment]
Bug has been fixed in 2.0.2 which came out a few hours ago.

**Comment by ghost** [comment]
Please be aware that this bug has not been fixed in 2.0.2

**Comment by Shrimpstress** [comment]
What type of stuff is it connecting to?

**Comment by ghost** [comment]
Chairs, tables, fans, couches, etc. Pretty much everything.

**Comment by Shrimpstress** [comment]
My bad, I thought you were referring to the fencing from my mod which had similar issues instead of vanilla fences. I found a fix for it already and will release a build within the next 30 minutes or so.

**Comment by Shrimpstress** [comment]
2.0.3 is out now which should /actually/ fix the bug this time. Sorry about that xD.
