### ISSUE TITLE
[1.12.2] Light Switches Face Incorrect Direction Visually

### ISSUE THREAD

**Issue by Hitel98** [Zundrel/How-Bout-That-Furniture#5]
The thing is, that the light switches always look at the same direction after an update of forge and several mods... Those other mods really not too many, but i'm not sure if the forge update caused this, or another mod...

**Comment by Hitel98** [comment]
![2017-12-24_08 27 12](https://user-images.githubusercontent.com/30383110/34324972-95207330-e884-11e7-83bc-78a9b9b0c9ac.png)
![2017-12-24_08 27 18](https://user-images.githubusercontent.com/30383110/34324973-954a7d74-e884-11e7-8f96-8c16b171d181.png)
![2017-12-24_08 27 32](https://user-images.githubusercontent.com/30383110/34324974-956dba8c-e884-11e7-9c19-504bec9c43f0.png)
![2017-12-24_08 27 38](https://user-images.githubusercontent.com/30383110/34324975-9593616a-e884-11e7-9879-62b7caa0528d.png)
![2017-12-24_08 27 42](https://user-images.githubusercontent.com/30383110/34324976-95b58f42-e884-11e7-80ad-19ac473eccdf.png)



That's what i talking about


PS:using an outdated forge fixes the problem, and i will use that outdated version of forge until a new version comes out of your mod

**Comment by Shrimpstress** [comment]
Closing this because of a workaround isn't really a great idea. I'll look into it. May take a bit because of how close to Christmas it is. I have family stuff both today and tomorrow.

**Comment by Shrimpstress** [comment]
May I ask what Forge version you were using before you updated, and what forge version you were using after updating?

**Comment by Hitel98** [comment]
1.12.2-forge1.12.2-14.23.0.2552 | before
1.12.2-forge1.12.2-14.23.1.2581 | after

Sry for replying a bit lately

**Comment by Shrimpstress** [comment]
It’s fine. Waiting on https://github.com/MinecraftForge/MinecraftForge/pull/4629 to fix the issue.

**Comment by Shrimpstress** [comment]
Upgrading to Forge 14.23.1.2585 will fix the issue. Sorry for the wait.

**Comment by Hitel98** [comment]
Thanks for the opportunity of the reporting
